<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Scope\Event;

final class ScopeWasRemoved extends \Prooph\EventSourcing\AggregateChanged
{
    protected $messageName = 'AulaSoftwareLibre\Iam\Domain\Scope\Event\ScopeWasRemoved';

    protected $payload = [];

    private $scopeId;

    public function scopeId(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId
    {
        if (null === $this->scopeId) {
            $this->scopeId = \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId::fromString($this->aggregateId());
        }

        return $this->scopeId;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId $scopeId): ScopeWasRemoved
    {
        return new self($scopeId->toString(), [
        ]);
    }

    protected function setPayload(array $payload): void
    {
        $this->payload = $payload;
    }
}
