<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Scope\Event;

final class ScopeWasCreated extends \Prooph\EventSourcing\AggregateChanged
{
    protected $messageName = 'AulaSoftwareLibre\Iam\Domain\Scope\Event\ScopeWasCreated';

    protected $payload = [];

    private $scopeId;
    private $name;
    private $shortName;

    public function scopeId(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId
    {
        if (null === $this->scopeId) {
            $this->scopeId = \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId::fromString($this->aggregateId());
        }

        return $this->scopeId;
    }

    public function name(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\Name
    {
        if (null === $this->name) {
            $this->name = \AulaSoftwareLibre\Iam\Domain\Scope\Model\Name::fromString($this->payload['name']);
        }

        return $this->name;
    }

    public function shortName(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\ShortName
    {
        if (null === $this->shortName) {
            $this->shortName = \AulaSoftwareLibre\Iam\Domain\Scope\Model\ShortName::fromString($this->payload['shortName']);
        }

        return $this->shortName;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId $scopeId, \AulaSoftwareLibre\Iam\Domain\Scope\Model\Name $name, \AulaSoftwareLibre\Iam\Domain\Scope\Model\ShortName $shortName): ScopeWasCreated
    {
        return new self($scopeId->toString(), [
            'name' => $name->toString(),
            'shortName' => $shortName->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['name']) || !\is_string($payload['name'])) {
            throw new \InvalidArgumentException("Key 'name' is missing in payload or is not a string");
        }

        if (!isset($payload['shortName']) || !\is_string($payload['shortName'])) {
            throw new \InvalidArgumentException("Key 'shortName' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
