#!/usr/bin/env bash

echo "GATA pre commit hook start"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    ERROR=0
    for line in $(git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3-); do
        if ! $PHP_CS_FIXER fix --verbose --dry-run "$line";
        then
            ERROR=1
        fi
        $PHP_CS_FIXER fix --quiet "$line";
    done
    if [ $ERROR -ne 0 ]
    then
        echo "**********************************************"
        echo "php-cs-fixer fixed some files, commit aborted"
        echo "**********************************************"
        exit 1
    fi
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo ""
    echo "  composer require --dev friendsofphp/php-cs-fixer"
    echo ""
fi

echo "GATA pre commit hook finish"
