parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true
        mappings:
            ReadModel:
                is_bundle: false
                type: 'xml'
                dir: '%kernel.root_dir%/Resources/config/doctrine'
                prefix: 'AulaSoftwareLibre\Iam\Infrastructure\ReadModel\View'
                alias: 'ReadModel'

services:
    _defaults:
        public: true
    # Repositories

    ## Write model
    AulaSoftwareLibre\Iam\Application\User\Repository\Users: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\UsersEventStore'
    AulaSoftwareLibre\Iam\Application\Scope\Repository\Scopes: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\ScopesEventStore'
    AulaSoftwareLibre\Iam\Application\Role\Repository\Roles: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\RolesEventStore'

    ## Read model
    AulaSoftwareLibre\Iam\Infrastructure\ReadModel\Repository\UserViews: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\Repository\UserViewsRepository'
    AulaSoftwareLibre\Iam\Infrastructure\ReadModel\Repository\ScopeViews: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\Repository\ScopeViewsRepository'
    AulaSoftwareLibre\Iam\Infrastructure\ReadModel\Repository\RoleViews: '@AulaSoftwareLibre\Iam\Infrastructure\Doctrine\Repository\RoleViewsRepository'
