prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'
            repositories:
                AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\UsersEventStore:
                    aggregate_type: 'AulaSoftwareLibre\Iam\Domain\User\Model\User'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\ScopesEventStore:
                    aggregate_type: 'AulaSoftwareLibre\Iam\Domain\Scope\Model\Scope'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
                AulaSoftwareLibre\Iam\Infrastructure\Doctrine\EventStore\RolesEventStore:
                    aggregate_type: 'AulaSoftwareLibre\Iam\Domain\Role\Model\Role'
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
