prooph_service_bus:
    command_buses:
        default_command_bus: ~
    event_buses:
        default_event_bus: ~
    query_buses:
        default_query_bus: ~

services:
    _defaults:
        public: true
        autowire: true

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.default_command_bus'
    Prooph\ServiceBus\EventBus: '@prooph_service_bus.default_event_bus'
    Prooph\ServiceBus\QueryBus: '@prooph_service_bus.default_query_bus'

    # Autoregister your message handlers here
    # Make sure App\Messaging\* services are not overriden in `config/services.yaml`
    # Read more at https://github.com/prooph/service-bus-symfony-bundle/blob/master/doc/routing.md
    #
    command_handlers:
        resource: '../../src/Application/**/Command/*Handler.php'
        namespace: 'App\Application\'
        tags:
            - { name: 'prooph_service_bus.default_command_bus.route_target', message_detection: true }
