language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

env:
  global:
    - APP_ENV=test
    - APP_SECRET=SECRET

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer validate --strict
  - mkdir -p build/logs
  - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
  - vendor/bin/phpspec run --format=pretty --ansi --no-code-generation
  - vendor/bin/behat --strict --colors

after_success:
  - travis_retry php vendor/bin/php-coveralls
