<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Application\Scope\Command;

final class RemoveScope extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    protected $messageName = 'AulaSoftwareLibre\Iam\Application\Scope\Command\RemoveScope';

    public function scopeId(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId
    {
        return \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId::fromString($this->payload['scopeId']);
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId $scopeId): RemoveScope
    {
        return new self([
            'scopeId' => $scopeId->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['scopeId']) || !\is_string($payload['scopeId'])) {
            throw new \InvalidArgumentException("Key 'scopeId' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
