services:
    _defaults:
        public: false

    AulaSoftwareLibre\DDD\Service\Prooph\Plugin\EventCollectorPlugin:
        public: true
        tags:
            { name: 'prooph_service_bus.event_bus.plugin' }

    Tests\Behat\Repository\:
        resource: '../tests/Behat/Repository'
