<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\User\Event;

final class UserWasCreated extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Iam\Domain\User\Event\UserWasCreated';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $userId;
    private $username;

    public function userId(): \AulaSoftwareLibre\Iam\Domain\User\Model\UserId
    {
        if (null === $this->userId) {
            $this->userId = \AulaSoftwareLibre\Iam\Domain\User\Model\UserId::fromString($this->aggregateId());
        }

        return $this->userId;
    }

    public function username(): \AulaSoftwareLibre\Iam\Domain\User\Model\Username
    {
        if (null === $this->username) {
            $this->username = \AulaSoftwareLibre\Iam\Domain\User\Model\Username::fromString($this->payload['username']);
        }

        return $this->username;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\User\Model\UserId $userId, \AulaSoftwareLibre\Iam\Domain\User\Model\Username $username): UserWasCreated
    {
        return new self($userId->toString(), [
            'username' => $username->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['username']) || !\is_string($payload['username'])) {
            throw new \InvalidArgumentException("Key 'username' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
