<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Domain\User\Event;

final class UserWasCreated extends \Prooph\EventSourcing\AggregateChanged
{
    protected $messageName = 'App\Domain\User\Event\UserWasCreated';

    protected $payload = [];

    private $userId;
    private $username;
    private $email;

    public function userId(): \App\Domain\User\Model\UserId
    {
        if (null === $this->userId) {
            $this->userId = \App\Domain\User\Model\UserId::fromString($this->aggregateId());
        }

        return $this->userId;
    }

    public function username(): \App\Domain\User\Model\Username
    {
        if (null === $this->username) {
            $this->username = \App\Domain\User\Model\Username::fromString($this->payload['username']);
        }

        return $this->username;
    }

    public function email(): \App\Domain\User\Model\Email
    {
        if (null === $this->email) {
            $this->email = \App\Domain\User\Model\Email::fromString($this->payload['email']);
        }

        return $this->email;
    }

    public static function with(\App\Domain\User\Model\UserId $userId, \App\Domain\User\Model\Username $username, \App\Domain\User\Model\Email $email): UserWasCreated
    {
        return new self($userId->toString(), [
            'username' => $username->toString(),
            'email' => $email->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['username']) || !\is_string($payload['username'])) {
            throw new \InvalidArgumentException("Key 'username' is missing in payload or is not a string");
        }

        if (!isset($payload['email']) || !\is_string($payload['email'])) {
            throw new \InvalidArgumentException("Key 'email' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
