<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Role\Event;

final class RoleWasAdded extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Iam\Domain\Role\Event\RoleWasAdded';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $roleId;
    private $scopeId;
    private $name;

    public function roleId(): \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId
    {
        if (null === $this->roleId) {
            $this->roleId = \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId::fromString($this->aggregateId());
        }

        return $this->roleId;
    }

    public function scopeId(): \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId
    {
        if (null === $this->scopeId) {
            $this->scopeId = \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId::fromString($this->payload['scopeId']);
        }

        return $this->scopeId;
    }

    public function name(): \AulaSoftwareLibre\Iam\Domain\Role\Model\Name
    {
        if (null === $this->name) {
            $this->name = \AulaSoftwareLibre\Iam\Domain\Role\Model\Name::fromString($this->payload['name']);
        }

        return $this->name;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId $roleId, \AulaSoftwareLibre\Iam\Domain\Scope\Model\ScopeId $scopeId, \AulaSoftwareLibre\Iam\Domain\Role\Model\Name $name): RoleWasAdded
    {
        return new self($roleId->toString(), [
            'scopeId' => $scopeId->toString(),
            'name' => $name->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['scopeId']) || !\is_string($payload['scopeId'])) {
            throw new \InvalidArgumentException("Key 'scopeId' is missing in payload or is not a string");
        }

        if (!isset($payload['name']) || !\is_string($payload['name'])) {
            throw new \InvalidArgumentException("Key 'name' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
