<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Role\Event;

final class RoleWasDescribed extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Iam\Domain\Role\Event\RoleWasDescribed';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $roleId;
    private $description;

    public function roleId(): \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId
    {
        if (null === $this->roleId) {
            $this->roleId = \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId::fromString($this->aggregateId());
        }

        return $this->roleId;
    }

    public function description(): \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleDescription
    {
        if (null === $this->description) {
            $this->description = \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleDescription::fromString($this->payload['description']);
        }

        return $this->description;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId $roleId, \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleDescription $description): RoleWasDescribed
    {
        return new self($roleId->toString(), [
            'description' => $description->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['description']) || !\is_string($payload['description'])) {
            throw new \InvalidArgumentException("Key 'description' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
