<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Role\Event;

final class RoleWasRemoved extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Iam\Domain\Role\Event\RoleWasRemoved';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $roleId;

    public function roleId(): \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId
    {
        if (null === $this->roleId) {
            $this->roleId = \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId::fromString($this->aggregateId());
        }

        return $this->roleId;
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId $roleId): RoleWasRemoved
    {
        return new self($roleId->toString(), [
        ]);
    }

    protected function setPayload(array $payload): void
    {
        $this->payload = $payload;
    }
}
