<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Scope\Model;

final class ShortName
{
    private $value;

    public function __construct(string $value)
    {
        if (1 === preg_match('/[^a-z]/', $value)) {
            throw new \InvalidArgumentException('Short name only accepts [a-z] characters');
        }

        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public static function fromString(string $shortName): ShortName
    {
        return new self($shortName);
    }

    public function equals(ShortName $shortName): bool
    {
        if (\get_class($this) !== \get_class($shortName)) {
            return false;
        }

        return $this->value === $shortName->value;
    }
}
