<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Application\User\Command;

final class PromoteUser extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'AulaSoftwareLibre\Iam\Application\User\Command\PromoteUser';

    protected $messageName = self::MESSAGE_NAME;

    public function userId(): \AulaSoftwareLibre\Iam\Domain\User\Model\UserId
    {
        return \AulaSoftwareLibre\Iam\Domain\User\Model\UserId::fromString($this->payload['userId']);
    }

    public function roleId(): \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId
    {
        return \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId::fromString($this->payload['roleId']);
    }

    public static function with(\AulaSoftwareLibre\Iam\Domain\User\Model\UserId $userId, \AulaSoftwareLibre\Iam\Domain\Role\Model\RoleId $roleId): PromoteUser
    {
        return new self([
            'userId' => $userId->toString(),
            'roleId' => $roleId->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['userId']) || !\is_string($payload['userId'])) {
            throw new \InvalidArgumentException("Key 'userId' is missing in payload or is not a string");
        }

        if (!isset($payload['roleId']) || !\is_string($payload['roleId'])) {
            throw new \InvalidArgumentException("Key 'roleId' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
