<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Role\Model;

final class RoleName
{
    private $value;

    public function __construct(string $value)
    {
        if (0 === preg_match('/^ROLE_[A-Z]+_[A-Z_]+$/', $value)) {
            throw new \InvalidArgumentException('Invalid role name format');
        }

        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public static function fromString(string $roleName): RoleName
    {
        return new self($roleName);
    }

    public function equals(RoleName $roleName): bool
    {
        if (\get_class($this) !== \get_class($roleName)) {
            return false;
        }

        return $this->value === $roleName->value;
    }
}
