<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `iam` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Iam\Domain\Role\Model;

final class RoleId
{
    private $uuid;

    public static function generate(): RoleId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $roleId): RoleId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($roleId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $roleId)
    {
        $this->uuid = $roleId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(RoleId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
